### ISSUE TITLE
[App Store Request] "need help !"

### ISSUE THREAD

**Issue by League2EB** [reitemeier/B_APP#2]
Dear developer,
Because my mother at home is visually impaired, and I have just been exposed to iOS development recently, I have not been able to create this application
I would like to ask whether this App has been released to the App Store?

**Comment by lukasbuehler** [comment]
Hi @League2EB 
No, we haven't released this App to the AppStore yet. We are still in the development phase and have a lot of ideas for this project. But if you need a similar app right now, we can recommend [Blindsquare](http://www.blindsquare.com).
